### ISSUE TITLE
Error while trying to open file for editing

### ISSUE THREAD

**Issue by adlermedrado** [textmate/rmate#37]
Hello,

I tried to use rmate today on one of my servers, I installed using the gem command (gem install rmate) and it installed without errors, but when I tried to open an file, I got the following error:

```
adler@adler:~$ rmate .bash_history 
adler@adler:~$ setsockopt TCP_NODELAY: Invalid argument
connect_to localhost port 52698: failed.
/var/lib/gems/1.9.1/gems/rmate-1.5.7/bin/rmate:158:in `readline': end of file reached (EOFError)
	from /var/lib/gems/1.9.1/gems/rmate-1.5.7/bin/rmate:158:in `connect_and_handle_cmds'
	from /var/lib/gems/1.9.1/gems/rmate-1.5.7/bin/rmate:207:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/rmate-1.5.7/bin/rmate:206:in `fork'
	from /var/lib/gems/1.9.1/gems/rmate-1.5.7/bin/rmate:206:in `<top (required)>'
	from /usr/local/bin/rmate:23:in `load'
	from /usr/local/bin/rmate:23:in `<main>'
```

**Comment by sorbits** [comment]
Did you setup port forwarding?

**Comment by adlermedrado** [comment]
Yes, I think I did it, below is my ~/.ssh/config

```
Host kurbads
    User jones
    HostName xxx.xxx.xxx.xxx
    RemoteForward 52698 localhost:52698
```
Is this right? Sorry if it is my fault.

**Comment by sorbits** [comment]
Setup the tunnel manually as described here: 
https://github.com/textmate/rmate#rmate

If that works, then it would seem your config is not working.

**Comment by adlermedrado** [comment]
Thank you for your help.
I did it now and I got exactly the same error.

**Comment by sorbits** [comment]
Is TextMate running on your local machine?

Test if you can connect to TextMate manually via: telnet 127.0.0.1 52698

**Comment by adlermedrado** [comment]
I tried and it didn't work, so I changed at Textmate's config to receive Access from Remote clients, before that this setting was client. 

After this change I was able to connect from telnet and from the remote host.

Thank you and sorry for not looking this setting before.

**Comment by rxm** [comment]
I was having the same problem.  The issue was not on the remote server, but my local machine (a macOS laptop).  What fixed it for me was changing the port number to something else and then back to what it was.  

In the TextMate > Preferences > Terminal pane I changed the Port: field to another high number (48000), hit tab, closed the Preference pane.  Re-opened it, changed the Port: filed back to what it used to be.
