### ISSUE TITLE
ruby 2.2 metadata missing

### ISSUE THREAD

**Issue by ryanrussell** [textmate/rmate#39]
gem install rmate
ERROR:  Error installing rmate:
	invalid gem: package metadata is missing in /usr/local/lib/ruby/gems/2.2.0/cache/rmate-1.5.7.gem

ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

I appreciate any suggestions to force... hopefully resolved soon!

**Comment by ryanrussell** [comment]
Anyone? Still unable to get rmate to work with ruby 2.2.2... works fine with 2.1.5

**Comment by sorbits** [comment]
You should try ask in a ruby forum about this, as a quick search shows 
that other gems are also affected, and I have no idea what changes they 
made in ruby 2.2 that would cause our current gem to no longer work.

**Comment by sorbits** [comment]
Any update on this? Does the gem (now) install with ruby 2.2 or do we need to adapt our gem creation process for new requirements?

**Comment by AJ-Acevedo** [comment]
I just tested rmate with ruby 2.2.3p173 on the local machine and ruby 2.2.2p95 on the remote machine.

Strange thing happened. When I ran rmate during an ssh session into the remote host it opened the target file in TextMate on the remote host.

The local machine is Mac OS 10.11.3
The remote machine is Mac OS 10.9.5

**Comment by sorbits** [comment]
Closing due to lack of follow-up from OP.
