### ISSUE TITLE
rmate fails from a Vagrant VM

### ISSUE THREAD

**Issue by brandondrew** [textmate/rmate#40]
I couldn't get the directions here working, and figured I must have misunderstood something, so I tried the directions here: http://hiltmon.com/blog/2013/11/09/textmate-2-basics/

That didn't work either, so it *appears* that the problem is with rmate. 

After attempting to `rmate .bash_profile` from `~` on the VM, I just get a new prompt, and after a little while of waiting I get:

~~~
$ /usr/local/bin/rmate:174:in `initialize': Connection timed out - connect(2) (Errno::ETIMEDOUT)
	from /usr/local/bin/rmate:174:in `new'
	from /usr/local/bin/rmate:174:in `connect_and_handle_cmds'
	from /usr/local/bin/rmate:228:in `block in <main>'
	from /usr/local/bin/rmate:227:in `fork'
	from /usr/local/bin/rmate:227:in `<main>'
~~~

Here is my `.ssh/config` for the Vagrant VM.  All normal `vagrant` commands work, so I'm quite sure everything is good in that regard, but using the `rmate` command from inside the Vagrant VM fails.

~~~
Host ads
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/brandon/Code/ad-related-reports/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  
  RemoteForward 52698 127.0.0.1:52698
~~~

TextMate does have permission to allow incoming connections in the Firewall settings.  I even tried turning off the firewall, but that made no difference.

**Comment by sorbits** [comment]
For an out-of-the-box config, set TextMate to support connections from 
remote hosts (Preferences → Terminal) and use `--host=auto` with rmate 
(from vagrant), and it should work.

If you do not want to allow connections from remote clients then you 
must setup a tunnel between your machine and vagrant. I don’t know 
off-hand how this is done.

If you do not want to specify `--host=auto` each time then setup this as 
the default (see the README).

If you think there is a bug with rmate then please see 
https://github.com/textmate/textmate/wiki/Writing-Bug-Reports

**Comment by brandondrew** [comment]
"Accept rmate connections" was turned on.  

This was my `~/rmate.rc` file:

~~~
host: auto                   # Prefer host from SSH_CONNECTION over localhost
port: 52698
unixsocket: ~/.rmate.socket  # Use this socket file if it exists
~~~

Sorry: forgot to mention those two things.

As for the tunnel, that was configured in the `~/.ssh/config` file line below:
~~~
RemoteForward 52698 127.0.0.1:52698
~~~

**Comment by sorbits** [comment]
> "Accept rmate connections" was turned on.

And “access for” is set to *remote clients*?

**Comment by AJ-Acevedo** [comment]
Try running rmate as root.

**Comment by brandondrew** [comment]
I'm fairly confident I tried that, but I'll try again just to make sure...
thanks!

On Tue, Jun 30, 2015 at 8:33 PM, AJ <notifications@github.com> wrote:

> Try running rmate as root.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/textmate/rmate/issues/40#issuecomment-117378656>.
>



-- 
Brandon Zylstra
brandon.zylstra@gmail.com

**Comment by sorbits** [comment]
I don’t think root should make a difference, but as mentioned above, 
you must set TextMate to allow access for remote clients, if you do not 
setup a tunnel (which I do not know how you would do with a virtual 
machine).

If you use the latest version of rmate, the error shown when it fails to 
connect should give a better idea of what failed.
