### ISSUE TITLE
No warning when save fails

### ISSUE THREAD

**Issue by tiktuk** [textmate/rmate#41]
When a file is opened in TextMate via rmate and saving fails due to the network connection being lost or rmate not having enough permissions, it still looks like TextMate saves the file perfectly.

It could be great if there was a warning when it doesn't succeed. It could lead to data loss if one closes a file with changes that has only seemingly been committed to disk.

Using TextMate 2.0-beta.7.9 and rmate version 1.5.8.

**Comment by sorbits** [comment]
Same issue as #17
