### ISSUE TITLE
EOFError while running rmate

### ISSUE THREAD

**Issue by kpagacz** [textmate/rmate#51]
I have been trying to setup Sublime Text 3 on my local Windows 10 machine to work remotely on files on my Ubuntu 16.04 LTE server (google cloud compute engine instance). I followed these instructions: https://github.com/henrikpersson/rsub and https://github.com/textmate/rmate

I have decided to use a standalone bash version (though I apparently still needed to install ruby environment).

I have setup my rmate script in /bin/ catalogue, but when I try to run the command rmate, I get the following end of a line error:

    /bin/rmate:145:in `readline': end of file reached (EOFError)
        from /bin/rmate:145:in `handle_cmd'
        from /bin/rmate:180:in `connect_and_handle_cmds'
        from /bin/rmate:223:in `block in <main>'
        from /bin/rmate:222:in `fork'
        from /bin/rmate:222:in `<main>'

I have tried simply reinstalling the script from the link provided, but it didn't help. I also made sure that the rest of my installation: config file on my local machine and my firewall rules and sshd config files are correct.

I would be grateful if you pointed me in the directoin of what I am missing.

**Comment by sorbits** [comment]
`rmate` is written for TextMate (a Mac text editor), we do not offer support for using `rmate` with other software.
