### ISSUE TITLE
Alignment issues on python code

### ISSUE THREAD

**Issue by PREM1980** [textmate/rmate#52]
Hi
I use rmate to edit my files in the Linux server. I'm able to successfully open the files but for reason the python code is not aligned properly. Few lines are not aligned properly.

Here is a thread about this issue. Not sure what needs to be changed in sublime to make it work correctly.

https://askubuntu.com/questions/959866/files-improperly-aligned-after-transfer-via-ftp?noredirect=1#comment1533479_959866

**Comment by sorbits** [comment]
`rmate` is written for TextMate (a Mac text editor), if you use it with third party software then you should contact your software vendor for support.
