### ISSUE TITLE
I've been experiencing a very similar problem. Thank you for your post with the --wait and --verbose options! My files were just disappearing, and I couldn't figure out why!

### ISSUE THREAD

**Issue by josh2691** [textmate/rmate#61]
I've been experiencing a very similar problem. Thank you for your post with the --wait and --verbose options! My files were just disappearing, and I couldn't figure out why!
```
$ls -l
-rwxrwxr-x 1 bfletcher bfletcher     0 Aug 22 11:20 temp_file.py
```
Error with `$rmate --view --wait temp_file.py`:
```
touch: cannot touch ‘/tmp/rmate.11068.90017’: Permission denied
/usr/local/bin/rmate: line 362: /tmp/rmate.11068.90017: Permission denied
Saving temp_file.py
cat: /tmp/rmate.11068.90017: No such file or directory
rm: cannot remove ‘/tmp/rmate.11068.90017’: No such file or directory
```

_Originally posted by @squishbug in https://github.com/textmate/rmate/issues/53#issuecomment-415075803_

**Comment by sorbits** [comment]
Please 👍 comments that you like, instead of creating new issues.
